name: Firebase CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, upgrade -R eslint, build and test
      run: |
        yarn install
        yarn upgrade -R eslint
        yarn build
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "index.html"
          target: "200.html"
      - name: Deploy to telemedicine-doctor.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'telemedicine-doctor.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
